### ISSUE TITLE
Featured images not appearing on single posts

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zillah#156]
Users have asked why the images (when they use the option to pull the first image if featured isn't set) isn't appear in the post itself. Patch incoming.

**Comment by rodica-andronache** [comment]
@HardeepAsrani what you did it's working ok. The problem is, i'm not sure if this is how it's supposed to work. Right now, if the "Get 1st image in the post as featured." option is checked, the featured image appears on the blog, but not on the single. And I suppose, this is done like this, because we don't want to have the same image duplicated on single. I'm not sure. @ineagu what do you say?

**Comment by HardeepAsrani** [comment]
Yes, I have the same doubt. So yes, it's up to us to make a decision about this.

**Comment by ineagu** [comment]
I agree that this is not needed.
